### ISSUE TITLE
Please rewrite without threads

### ISSUE THREAD

**Issue by patrakov** [tievolu/sqm-autorate#1]
On aarch64 and some other architectures, OpenWRT perl is built without threads by default, and therefore this script does not work. It may be a good idea to rewrite it as a single-threaded program that uses `select` to do multiple network I/O operations in parallel.

**Comment by tievolu** [comment]
> It may be a good idea to rewrite it as a single-threaded program

I don't object in principle to eliminating the multiple threads from this script - it certainly wasn't easy to get them working properly. The intermittent deadlocks when forking to run system commands were a nightmare.

However, I don't have any experience working with non-blocking IO in perl or anywhere else, so a complete rewrite of this script is unlikely to happen any time soon.

I didn't know that perl threads weren't enabled on some platforms. It looks like a very conservative approach was taken when enabling them back in 2015:

https://github.com/openwrt/packages/pull/854

It seems that perl threads are not enabled on any platform where the submitter of that PR was not able to personally test them. Maybe that decision can be revisited?

**Comment by amaumene** [comment]
Fyi, threads is now enable on aarch64 and the script works just fine :)
